server:
  port: 8090
  servlet:
    context-path: /example

spring:
  profiles:
    active: dev

  dynamic:
    thread-pool:
      enable: true
      banner: true
      check-state-interval: 3
      notify-platforms:
        - platform: 'WECHAT'
          secret-key: 1d307bfa-815f-4662-a2e5-99415e947bb8
        - platform: 'DING'
          secret-key: 56417ebba6a27ca352f0de77a2ae9da66d01f39610b5ee8a6033c60ef9071c55
      apollo:
        namespace: xxxx
      config-file-type: yml
      executors:
        - thread-pool-id: 'message-consume'
          core-pool-size: 1
          maximum-pool-size: 1
          queue-capacity: 1
          execute-time-out: 1000
          blocking-queue: 'LinkedBlockingQueue'
          rejected-handler: 'AbortPolicy'
          keep-alive-time: 6691
          allow-core-thread-time-out: true
          thread-name-prefix: 'message-consume'
          notify:
            is-alarm: true
            active-alarm: 80
            capacity-alarm: 80
            interval: 8
            receives:
              WECHAT: 'xxx' # Fill in the enterprise weChat userId
              DING: 'xxx' # phone

