server:
  port: 8088

spring:
  profiles:
    active: dev
  application:
    name: dynamic-threadpool-example
  dynamic:
    thread-pool:
      alarms:
        - type: DING
          url: https://oapi.dingtalk.com/robot/send?access_token=
          token: 4a582a588a161d6e3a1bd1de7eea9ee9f562cdfcbe56b6e72029e7fd512b2eae
      server-addr: http://localhost:6691
      namespace: common
      item-id: message-center
